import events as e

APPROACH_COIN = 'APPROACH_COIN'
MOVED_AWAY_FROM_COIN = 'MOVED_AWAY_FROM_COIN'

APPROACH_CRATE = 'APPROACH_CRATE'

rewards = {
    e.COIN_COLLECTED: 25,
    e.MOVED_UP: -2,
    e.MOVED_DOWN: -2,
    e.MOVED_LEFT: -2,
    e.MOVED_RIGHT: -2,
    e.INVALID_ACTION: -7,
    e.WAITED: -10,
    APPROACH_COIN: 5,
    MOVED_AWAY_FROM_COIN: -5,
    e.SURVIVED_ROUND: 5,
    e.BOMB_DROPPED: 2,
    e.BOMB_EXPLODED: 2,
    e.COIN_FOUND: 10,
    e.CRATE_DESTROYED: 3,
    e.GOT_KILLED: -100,
    e.KILLED_SELF: -100,
    # e.KILLED_OPPONENT: 20,
    # e.OPPONENT_ELIMINATED: 0,
}
