import events as e

APPROACH_COIN = 'APPROACH_COIN'
MOVED_AWAY_FROM_COIN = 'MOVED_AWAY_FROM_COIN'

APPROACH_CRATE = 'APPROACH_CRATE'
MOVED_AWAY_FROM_CRATE = 'MOVED_AWAY_FROM_CRATE'

APPROACH_BOMB = 'APPROACH_BOMB'
MOVED_AWAY_FROM_BOMB = 'MOVED_AWAY_FROM_BOMB'

IN_DANGER = 'IN_DANGER'
MOVE_IN_DANGER = 'MOVE_IN_DANGER'

rewards = {
    e.COIN_COLLECTED: 25,
    e.MOVED_UP: -1,
    e.MOVED_DOWN: -1,
    e.MOVED_LEFT: -1,
    e.MOVED_RIGHT: -1,
    e.INVALID_ACTION: -10,
    e.WAITED: -15,
    APPROACH_COIN: 9,
    MOVED_AWAY_FROM_COIN: -9,
    APPROACH_CRATE: 30,
    MOVED_AWAY_FROM_CRATE: -30,
    APPROACH_BOMB: -30,
    MOVED_AWAY_FROM_BOMB: 25,
    IN_DANGER: -20,
    MOVE_IN_DANGER: -35,
    e.SURVIVED_ROUND: 5,
    e.BOMB_DROPPED: 30,
    e.BOMB_EXPLODED: -10,
    e.COIN_FOUND: 30,
    e.CRATE_DESTROYED: 35,
    e.GOT_KILLED: -200,
    e.KILLED_SELF: -200,
    # e.KILLED_OPPONENT: 20,
    # e.OPPONENT_ELIMINATED: 0,
}
